name: scrape-daily

on:
  schedule:
    - cron: "15 23 * * *" # 09:15 Australia/Sydney (UTC-10 offset in action below)
  workflow_dispatch:

jobs:
  scrape:
    runs-on: ubuntu-latest
    env:
      TZ: Australia/Sydney
    permissions:
      contents: write
      pages: write
      id-token: write
    steps:
      - uses: actions/checkout@v4

      - name: Setup Python
        uses: actions/setup-python@v5
        with:
          python-version: "3.12"

      - name: Install deps
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt
          python -m playwright install --with-deps chromium

      - name: Run scraper
        run: python scrape.py

      - name: Commit artifacts
        run: |
          git config user.name "github-actions[bot]"
          git config user.email "41898282+github-actions[bot]@users.noreply.github.com"
          git add out/history.json out/latest.json out/index.html
          git commit -m "update data $(date -u +'%Y-%m-%dT%H:%M:%SZ')" || echo "No changes"
          git push

      - name: Upload Pages artifact
        uses: actions/upload-pages-artifact@v3
        with:
          path: out

      - name: Deploy to GitHub Pages
        uses: actions/deploy-pages@v4
